twig:
  default_path: "%kernel.project_dir%/templates"
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  exception_controller: null
  globals:
    base_url: "%kernel.project_dir%"
    cart_getter_service: "@app.cart.getter"
    product_getter_service: "@app.product.getter"
    producer_getter_service: "@app.producer.getter"
    category_getter_service: "@app.category.getter"
