index:
  path: /
  controller: App\Controller\IndexController::index
login:
  path: /login
  controller: App\Controller\LoginController::index
signIn:
  path: /sign-in
  controller: App\Controller\LoginController::signIn
register:
  path: /register
  controller: App\Controller\LoginController::register
product:
  path: /product/{id}
  controller: App\Controller\ProductController::index
